# COMMAND LINE RULES: ./swiftlint rules
# RULES URL: https://github.com/realm/SwiftLint/blob/master/Rules.md
# RULES CONFIG URL: https://github.com/realm/SwiftLint/tree/master/Source/SwiftLintFramework/Rules/RuleConfigurations

excluded: # paths to ignore during linting
  - Pods
  - R.generated.swift

disabled_rules:
    - large_tuple
    - todo # disabled for now

opt_in_rules:  # some rules are only opt-in
    # Conditional statements should always return on the next line
    - conditional_returns_on_newline
    # Force unwrapping should be avoided.
    - force_unwrapping
    # Implicitly unwrapped optionals should be avoided when possible.
    - implicitly_unwrapped_optional
    # nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant
    - redundant_nil_coalescing
    # Some methods should not call super
    - prohibited_super_call
    # Some overridden methods should always call super
    - overridden_super_call
    # Prefer using .first(where:) over .filter { }.first in collections.
    - first_where
    # Prefer checking isEmpty over comparing count to zero.
    - empty_count
    # Closure expressions should have a single space inside each brace.
    - closure_spacing
    # Closure end should have the same indentation as the line that started it.
    - closure_end_indentation
    # Explicitly calling .init() should be avoided.
    - explicit_init
    # Function parameters should be aligned vertically if they're in multiple lines in a method call.
    - vertical_parameter_alignment_on_call
    # Functions and methods parameters should be either on the same line, or one per line.
    - multiline_parameters
    # IBOutlets should be private to avoid leaking UIKit to higher layers.
    - private_outlet
    - private_action
    # Closure parameters should be on the same line as opening brace.
    - closure_parameter_position
    # A fatalError call should have a message.
    - fatal_error_message
    # Prefer contains over first(where:) != nil
    - contains_over_first_not_nil
    # Array and dictionary literal end should have the same indentation as the line that started it.
    - literal_expression_end_indentation
    # Prefer using min() or max() over sorted().first or sorted().last
    - sorted_first_last
    # Prefer checking isEmpty over comparing string to an empty string literal.
    - empty_string
    # Prefer using AnyObject over class for class-only protocols.
    - anyobject_protocol

trailing_whitespace:
    ignores_empty_lines: true
    ignores_comments: true
    ignores_urls: true

line_length:
    warning: 160
    error: 250
    ignores_comments: true
    ignores_function_declarations: false
    ignores_urls: true
    ignores_interpolated_strings: true

vertical_whitespace:
    max_empty_lines: 2

identifier_name:
    min_length: 2
    max_length: 45

type_name:
    max_length:
        warning: 50
        error: 60

nesting:
    type_level:
        warning: 2

file_length:
    warning: 400
    error: 600
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15

function_parameter_count:
    warning: 6
